In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Zaid-N-Ansari/PG-Mini-Project/refs/heads/main/Data/GroceryTDS.csv?token=GHSAT0AAAAAADCE7OAHWN5ABAWJDZE2TTPA2AMNSYQ', header=None)

In [3]:
# df = df.drop(columns=['Unnamed: 0'])

In [4]:
# df.columns = df.columns.str.replace(' ', '_')

In [5]:
print(df.__len__())
df.sample(10)

7501

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
766,765.0,red wine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3429,3428.0,turkey,frozen vegetables,spaghetti,mineral water,eggs,antioxydant juice,french fries,frozen smoothie,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1839,1838.0,mineral water,french fries,cookies,shallot,low fat yogurt,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3594,3593.0,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1615,1614.0,burgers,spaghetti,avocado,pancakes,cake,fresh bread,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2410,2409.0,eggs,cake,rice,french fries,frozen smoothie,yogurt cake,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5500,5499.0,grated cheese,whole wheat rice,chocolate,french fries,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,365.0,mineral water,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
442,441.0,ground beef,whole wheat rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3439,3438.0,milk,frozen smoothie,white wine,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
te = TransactionEncoder()
te_array = te.fit(df).transform(df)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

TypeError: 'int' object is not iterable