In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
# df = pd.read_csv('https://raw.githubusercontent.com/Zaid-N-Ansari/PG-Mini-Project/refs/heads/main/Data/GroceryTDS.csv?token=GHSAT0AAAAAADCE7OAHWN5ABAWJDZE2TTPA2AMNSYQ', header=None)
df = pd.read_csv('../Data/GroceryTDS.csv', header=None)

In [3]:
# df = df.drop(columns=['Unnamed: 0'])

In [4]:
# df.columns = df.columns.str.replace(' ', '_')

In [3]:
print(df.__len__())
df.sample(10)

7501

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
3790,3789.0,whole wheat pasta,frozen smoothie,brownies,energy drink,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6798,6797.0,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5012,5011.0,burgers,shrimp,tomatoes,mineral water,avocado,pancakes,whole wheat rice,cooking oil,yogurt cake,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4415,4414.0,energy bar,candy bars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2696,2695.0,sandwich,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6362,6361.0,burgers,energy bar,whole wheat rice,bug spray,french fries,hot dogs,sparkling water,shampoo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2662,2661.0,frozen vegetables,vegetables mix,eggs,escalope,low fat yogurt,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3129,3128.0,gums,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5916,5915.0,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2600,2599.0,tomatoes,mineral water,avocado,meatballs,eggs,cereals,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
te = TransactionEncoder()
te_array = te.fit(df).transform(df)
df_encoded = pd.DataFrame(te_array, columns=te.columns_)

TypeError: 'int' object is not iterable